spring:
  application:
    name: wallet
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: wallet
    password: wallet
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379

server:
  error:
    whitelabel:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
